// Generated by https://quicktype.io

namespace SpotifyApi.NetCore
{
    using System;
    using Newtonsoft.Json;

    public partial class CurrentPlaybackContext
    {
        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }

        [JsonProperty("device")]
        public Device Device { get; set; }

        [JsonProperty("progress_ms")]
        //[JsonConverter(typeof(ParseStringConverter))]
        public long ProgressMs { get; set; }

        [JsonProperty("is_playing")]
        public bool IsPlaying { get; set; }

        [JsonProperty("currently_playing_type")]
        public string CurrentlyPlayingType { get; set; }

        [JsonProperty("item")]
        public Track Item { get; set; }

        [JsonProperty("shuffle_state")]
        public bool ShuffleState { get; set; }

        [JsonProperty("repeat_state")]
        public string RepeatState { get; set; }

        [JsonProperty("context")]
        public Context Context { get; set; }
    }

    public partial class Context
    {
        [JsonProperty("external_urls")]
        public ExternalUrls ExternalUrls { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("uri")]
        public string Uri { get; set; }
    }

}
