// Generated by https://quicktype.io
using Newtonsoft.Json;

namespace SpotifyApi.NetCore
{
    /// <summary>
    /// Device Object
    /// </summary>
    /// <remarks> https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/ </remarks>
    public partial class Device
    {
        /// <summary>
        /// The device ID. This may be null.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// If this device is the currently active device.
        /// </summary>
        [JsonProperty("is_active")]
        public bool IsActive { get; set; }

        /// <summary>
        /// If this device is currently in a private session.
        /// </summary>
        [JsonProperty("is_private_session")]
        public bool IsPrivateSession { get; set; }

        /// <summary>
        /// Whether controlling this device is restricted. At present if this is “true” then no Web 
        /// API commands will be accepted by this device.
        /// </summary>
        [JsonProperty("is_restricted")]
        public bool IsRestricted { get; set; }

        /// <summary>
        /// The name of the device.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Device type, such as “Computer”, “Smartphone” or “Speaker”.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        /// <summary>
        /// The current volume in percent. This may be null.
        /// </summary>
        [JsonProperty("volume_percent", NullValueHandling = NullValueHandling.Ignore)]
        public int? VolumePercent { get; set; }
    }
}
