// Generated by https://quicktype.io

namespace SpotifyApi.NetCore
{
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Search Result.
    /// </summary>
    /// <remarks> https://developer.spotify.com/documentation/web-api/reference/search/search/ </remarks>
    public partial class SearchResult
    {
        [JsonProperty("artists")]
        public ArtistsSearchResult Artists { get; set; }

        [JsonProperty("albums")]
        public AlbumsSearchResult Albums { get; set; }

        [JsonProperty("tracks")]
        public TracksSearchResult Tracks { get; set; }

        [JsonProperty("playlists")]
        public PlaylistsSearchResult Playlists { get; set; }
    }

    /// <summary>
    /// Artists Search Result.
    /// </summary>
    public partial class ArtistsSearchResult
    {
        [JsonProperty("href")]
        public string Href { get; set; }

        [JsonProperty("items")]
        public Artist[] Items { get; set; }

        [JsonProperty("limit")]
        public int Limit { get; set; }

        [JsonProperty("next")]
        public string Next { get; set; }

        [JsonProperty("offset")]
        public int Offset { get; set; }

        [JsonProperty("previous")]
        public string Previous { get; set; }

        [JsonProperty("total")]
        public int Total { get; set; }
    }

    /// <summary>
    /// Albums Search Result.
    /// </summary>
    public partial class AlbumsSearchResult
    {
        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("items")]
        public Album[] Items { get; set; }

        [JsonProperty("limit")]
        public long Limit { get; set; }

        [JsonProperty("next")]
        public Uri Next { get; set; }

        [JsonProperty("offset")]
        public long Offset { get; set; }

        [JsonProperty("previous")]
        public object Previous { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }
    }

    /// <summary>
    /// Tracks Search Result.
    /// </summary>
    public partial class TracksSearchResult
    {
        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("items")]
        public Track[] Items { get; set; }

        [JsonProperty("limit")]
        public long Limit { get; set; }

        [JsonProperty("next")]
        public Uri Next { get; set; }

        [JsonProperty("offset")]
        public long Offset { get; set; }

        [JsonProperty("previous")]
        public object Previous { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }
    }

    /// <summary>
    /// Playlists Search Result
    /// </summary>
    public partial class PlaylistsSearchResult
    {
        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("items")]
        public PlaylistSimplified[] Items { get; set; }

        [JsonProperty("limit")]
        public long Limit { get; set; }

        [JsonProperty("next")]
        public Uri Next { get; set; }

        [JsonProperty("offset")]
        public long Offset { get; set; }

        [JsonProperty("previous")]
        public object Previous { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }
    }
}
