// Generated by https://quicktype.io

namespace SpotifyApi.NetCore
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TrackAudioAnalysis
    {
        [JsonProperty("bars")]
        public Bar[] Bars { get; set; }

        [JsonProperty("beats")]
        public Bar[] Beats { get; set; }

        [JsonProperty("meta")]
        public Meta Meta { get; set; }

        [JsonProperty("sections")]
        public Dictionary<string, double>[] Sections { get; set; }

        [JsonProperty("segments")]
        public Segment[] Segments { get; set; }

        [JsonProperty("tatums")]
        public Bar[] Tatums { get; set; }

        [JsonProperty("track")]
        public AudioAnalysisTrack Track { get; set; }
    }

    public partial class Bar
    {
        [JsonProperty("start")]
        public double Start { get; set; }

        [JsonProperty("duration")]
        public double Duration { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }
    }

    public partial class Meta
    {
        [JsonProperty("analyzer_version")]
        public string AnalyzerVersion { get; set; }

        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonProperty("detailed_status")]
        public string DetailedStatus { get; set; }

        [JsonProperty("status_code")]
        public long StatusCode { get; set; }

        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }

        [JsonProperty("analysis_time")]
        public double AnalysisTime { get; set; }

        [JsonProperty("input_process")]
        public string InputProcess { get; set; }
    }

    public partial class Segment
    {
        [JsonProperty("start")]
        public double Start { get; set; }

        [JsonProperty("duration")]
        public double Duration { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }

        [JsonProperty("loudness_start")]
        public double LoudnessStart { get; set; }

        [JsonProperty("loudness_max_time")]
        public double LoudnessMaxTime { get; set; }

        [JsonProperty("loudness_max")]
        public double LoudnessMax { get; set; }

        [JsonProperty("loudness_end")]
        public long LoudnessEnd { get; set; }

        [JsonProperty("pitches")]
        public double[] Pitches { get; set; }

        [JsonProperty("timbre")]
        public double[] Timbre { get; set; }
    }

    public partial class AudioAnalysisTrack
    {
        [JsonProperty("duration")]
        public double Duration { get; set; }

        [JsonProperty("sample_md5")]
        public string SampleMd5 { get; set; }

        [JsonProperty("offset_seconds")]
        public long OffsetSeconds { get; set; }

        [JsonProperty("window_seconds")]
        public long WindowSeconds { get; set; }

        [JsonProperty("analysis_sample_rate")]
        public long AnalysisSampleRate { get; set; }

        [JsonProperty("analysis_channels")]
        public long AnalysisChannels { get; set; }

        [JsonProperty("end_of_fade_in")]
        public long EndOfFadeIn { get; set; }

        [JsonProperty("start_of_fade_out")]
        public double StartOfFadeOut { get; set; }

        [JsonProperty("loudness")]
        public double Loudness { get; set; }

        [JsonProperty("tempo")]
        public double Tempo { get; set; }

        [JsonProperty("tempo_confidence")]
        public double TempoConfidence { get; set; }

        [JsonProperty("time_signature")]
        public long TimeSignature { get; set; }

        [JsonProperty("time_signature_confidence")]
        public long TimeSignatureConfidence { get; set; }

        [JsonProperty("key")]
        public long Key { get; set; }

        [JsonProperty("key_confidence")]
        public double KeyConfidence { get; set; }

        [JsonProperty("mode")]
        public long Mode { get; set; }

        [JsonProperty("mode_confidence")]
        public double ModeConfidence { get; set; }

        [JsonProperty("codestring")]
        public string Codestring { get; set; }

        [JsonProperty("code_version")]
        public double CodeVersion { get; set; }

        [JsonProperty("echoprintstring")]
        public string Echoprintstring { get; set; }

        [JsonProperty("echoprint_version")]
        public double EchoprintVersion { get; set; }

        [JsonProperty("synchstring")]
        public string Synchstring { get; set; }

        [JsonProperty("synch_version")]
        public long SynchVersion { get; set; }

        [JsonProperty("rhythmstring")]
        public string Rhythmstring { get; set; }

        [JsonProperty("rhythm_version")]
        public long RhythmVersion { get; set; }
    }

    
}
